---

- name: Install Python2
  apt:
    name: python2.7
    state: present
    force: yes
    update_cache: yes

- name: Install Python Pip
  apt:
    name: python-pip
    state: present
    force: yes
    update_cache: yes
  
- name: Install MongoDB
  apt:
    name: mongodb
    state: present
    force: yes
    update_cache: yes

- name: Install Flask
  pip:
    name: flask
    
- name: Install Flask Restful
  pip:
    name: flask-restful
    
- name: Install Flask Jsonpify
  pip:
    name: flask-jsonpify
    
- name: Install Pymongo
  pip:
    name: pymongo
