 version: "3"

 services:
   mongoservice:
     build: GameDataService/mongoservice
     ports:
       - "27017:27017"
   gamedataservice:
     build: GameDataService
     ports:
       - "5000:5000"
